# Тренувальний ноутбук

**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

У наборі використано інші числові дані, а також додано нові операції з NumPy.

## Підготовка

In [2]:
import numpy as np


## Завдання 1. Додавання, віднімання та множення векторів на число

Дано вектори:
```python
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
```

1. Знайдіть `a + b`.
2. Знайдіть `a - b`.
3. Помножте вектор `a` на число `4`.
4. Помножте вектор `b` на число `-2`.
5. Обчисліть поелементний добуток `a * b`.

In [4]:
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * 4 =", a * 4)
print("b * (-2) =", b * -2)
print("a * b =", a * b)

a + b = [10  4  4 13]
a - b = [ 4 -8  6  5]
a * 4 = [28 -8 20 36]
b * (-2) = [ -6 -12   2  -8]
a * b = [ 21 -12  -5  36]


## Завдання 2. Скалярний добуток і довжина векторів

Дано вектори:
```python
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])
```

1. Обчисліть скалярний добуток двома способами: `np.dot()` і оператором `@`.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами.

In [5]:
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])

dot_np = np.dot(u, v)
dot_op = u @ v
print("Скалярний добуток (np.dot):", dot_np)
print("Скалярний добуток (@):", dot_op)

norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
print("Норма u:", norm_u)
print("Норма v:", norm_v)

cos_theta = dot_np / (norm_u * norm_v)
print("Косинус кута:", cos_theta)

Скалярний добуток (np.dot): 31
Скалярний добуток (@): 31
Норма u: 7.0
Норма v: 6.48074069840786
Косинус кута: 0.6833434069749784


## Завдання 3. Основні дії з матрицями

Дано матриці:
```python
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
```

1. Обчисліть `A + B`.
2. Обчисліть `A - B`.
3. Обчисліть поелементний добуток `A * B`.
4. Помножте матрицю `A` на число `5`.
5. Знайдіть транспоновану матрицю `A`.

In [6]:
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])
B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])

print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A * B:\n", A * B)
print("A * 5:\n", A * 5)
print("A транспонована:\n", A.T)

A + B:
 [[4 3 5]
 [9 3 6]]
A - B:
 [[ 2  7 -7]
 [-5 -3  2]]
A * B:
 [[  3 -10  -6]
 [ 14   0   8]]
A * 5:
 [[15 25 -5]
 [10  0 20]]
A транспонована:
 [[ 3  2]
 [ 5  0]
 [-1  4]]


## Завдання 4. Матричне множення

Дано матриці:
```python
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])
```

1. Обчисліть матричний добуток `A @ B`.
2. Визначте форму результату.
3. Обчисліть елемент результату з індексами `[0, 1]` вручну через відповідний рядок `A` і стовпець `B` та перевірте його.

In [7]:
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])
B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

res = A @ B
print("A @ B:\n", res)
print("Форма результату:", res.shape)

manual_val = np.dot(A[0, :], B[:, 1])
print("Елемент [0, 1] вручну:", manual_val)
print("Перевірка:", manual_val == res[0, 1])

A @ B:
 [[17  7]
 [32  5]]
Форма результату: (2, 2)
Елемент [0, 1] вручну: 7
Перевірка: True


## Завдання 5. Циклічний зсув вектора

Дано вектор:
```python
v = np.array([12, 7, 19, 4, 11, 8])
```

1. Виконайте циклічний зсув на 2 позиції вправо.
2. Виконайте циклічний зсув на 3 позиції вліво.
3. Відновіть початковий вектор із результату першого зсуву.

Використайте `np.roll()`.

In [8]:
v = np.array([12, 7, 19, 4, 11, 8])

shift_right = np.roll(v, 2)
print("Зсув на 2 вправо:", shift_right)

shift_left = np.roll(v, -3)
print("Зсув на 3 вліво:", shift_left)

restored = np.roll(shift_right, -2)
print("Відновлений вектор:", restored)

Зсув на 2 вправо: [11  8 12  7 19  4]
Зсув на 3 вліво: [ 4 11  8 12  7 19]
Відновлений вектор: [12  7 19  4 11  8]


## Завдання 6. Сортування та індекси

Дано вектор:
```python
v = np.array([42, 17, 29, 8, 35, 23])
```

1. Відсортуйте елементи за зростанням.
2. Відсортуйте елементи за спаданням.
3. Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.

Використайте `np.sort()` та `np.argsort()`.

In [9]:
v = np.array([42, 17, 29, 8, 35, 23])

print("За зростанням:", np.sort(v))
print("За спаданням:", np.sort(v)[::-1])

idx_desc = np.argsort(v)[::-1]
print("Індекси за спаданням:", idx_desc)

За зростанням: [ 8 17 23 29 35 42]
За спаданням: [42 35 29 23 17  8]
Індекси за спаданням: [0 4 2 5 1 3]


## Завдання 7. Обмеження значень

Дано вектор:
```python
v = np.array([-12, -4, 3, 18, 27, 35, 48])
```

Обмежте всі значення діапазоном від `-5` до `30`: значення, менші за `-5`, мають стати `-5`, а більші за `30` — `30`.

Додатково визначте індекси елементів, які були змінені.

Використайте `np.clip()`.

In [10]:
v = np.array([-12, -4, 3, 18, 27, 35, 48])

v_clipped = np.clip(v, -5, 30)
print("Обмежений вектор:", v_clipped)

changed_indices = np.where(v != v_clipped)[0]
print("Індекси змінених елементів:", changed_indices)

Обмежений вектор: [-5 -4  3 18 27 30 30]
Індекси змінених елементів: [0 5 6]


## Завдання 8. Унікальні значення та частоти

Дано вектор:
```python
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
```

1. Знайдіть усі унікальні значення.
2. Визначте кількість появ кожного значення.
3. Знайдіть значення, яке трапляється найчастіше.

Використайте `np.unique(..., return_counts=True)`.

In [11]:
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])

vals, counts = np.unique(v, return_counts=True)
print("Унікальні значення:", vals)
print("Кількість появ:", counts)

most_freq = vals[np.argmax(counts)]
print("Найчастіше значення:", most_freq)

Унікальні значення: [2 4 7 9]
Кількість появ: [3 3 4 1]
Найчастіше значення: 7


## Завдання 9. Поворот матриці

Дано матрицю:
```python
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])
```

Отримайте:
1. матрицю, повернуту на 90° за годинниковою стрілкою;
2. матрицю, повернуту на 180°;
3. матрицю, повернуту на 90° проти годинникової стрілки.

Використайте `np.rot90()`.

In [12]:
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

print("90° за годинниковою:\n", np.rot90(A, k=-1))
print("\n180°:\n", np.rot90(A, k=2))
print("\n90° проти годинникової:\n", np.rot90(A, k=1))

90° за годинниковою:
 [[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]

180°:
 [[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]

90° проти годинникової:
 [[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


## Завдання 10. Додавання рамки до матриці

Дано матрицю:
```python
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
```

1. Додайте навколо матриці рамку шириною 1 елемент, заповнену значенням `-1`.
2. Окремо створіть рамку шириною 2 елементи, заповнену нулями.
3. Виведіть форми отриманих матриць.

Використайте `np.pad()`.

In [13]:
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])

pad1 = np.pad(A, pad_width=1, mode='constant', constant_values=-1)
pad2 = np.pad(A, pad_width=2, mode='constant', constant_values=0)

print("Рамка 1 (-1):\n", pad1)
print("Рамка 2 (0):\n", pad2)
print("Форми:", pad1.shape, pad2.shape)

Рамка 1 (-1):
 [[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]
Рамка 2 (0):
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Форми: (5, 5) (7, 7)


## Завдання 11. Перестановка рядків і стовпців

Дано матрицю:
```python
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])
```

1. Переставте рядки відповідно до `row_order`.
2. Після цього переставте стовпці відповідно до `col_order`.
3. За допомогою обернених перестановок відновіть початкову матрицю.

Для побудови оберненої перестановки використайте `np.argsort()`.

In [14]:
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])
row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

A_swapped = A[row_order, :][:, col_order]
print("Переставлена:\n", A_swapped)

inv_row = np.argsort(row_order)
inv_col = np.argsort(col_order)

A_restored = A_swapped[:, inv_col][inv_row, :]
print("\nВідновлена:\n", A_restored)

Переставлена:
 [[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]

Відновлена:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


## Завдання 12. Трикутні частини матриці

Дано матрицю:
```python
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])
```

1. Отримайте верхню трикутну частину разом із головною діагоналлю.
2. Отримайте нижню трикутну частину разом із головною діагоналлю.
3. Отримайте строго верхню та строго нижню частини.
4. Відновіть початкову матрицю з нижньої та строго верхньої частин.

Використайте `np.triu()` та `np.tril()`.

In [15]:
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

upper = np.triu(A)
lower = np.tril(A)
strict_upper = np.triu(A, k=1)
strict_lower = np.tril(A, k=-1)

print("Верхня з діагоналлю:\n", upper)
print("\nНижня з діагоналлю:\n", lower)
print("\nСтрого верхня:\n", strict_upper)
print("\nСтрого нижня:\n", strict_lower)

print("\nВідновлена матриця:\n", lower + strict_upper)

Верхня з діагоналлю:
 [[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]

Нижня з діагоналлю:
 [[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]

Строго верхня:
 [[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]

Строго нижня:
 [[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]

Відновлена матриця:
 [[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]


## Завдання 13. Зовнішній добуток векторів

Дано вектори:
```python
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])
```

1. Побудуйте матрицю зовнішнього добутку.
2. Визначте її форму.
3. Перевірте, що елемент `[2, 1]` дорівнює `a[2] * b[1]`.

Використайте `np.outer()`.

In [16]:
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

out_prod = np.outer(a, b)
print("Зовнішній добуток:\n", out_prod)
print("Форма:", out_prod.shape)

elem = a[2] * b[1]
print("Перевірка [2, 1]:", out_prod[2, 1] == elem)

Зовнішній добуток:
 [[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]
Форма: (4, 3)
Перевірка [2, 1]: True


## Завдання 14. Добуток Кронекера

Дано матриці:
```python
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])
```

1. Обчисліть добуток Кронекера `A` і `B`.
2. Обчисліть добуток Кронекера `B` і `A`.
3. Порівняйте результати та їх форми.

Використайте `np.kron()`.

In [17]:
A = np.array([
    [2, 1],
    [0, 3]
])
B = np.array([
    [1, 4],
    [2, 0]
])

kr_ab = np.kron(A, B)
kr_ba = np.kron(B, A)

print("A x B:\n", kr_ab)
print("\nB x A:\n", kr_ba)
print("\nФорми:", kr_ab.shape, kr_ba.shape)
print("Чи однакові:", np.allclose(kr_ab, kr_ba))

A x B:
 [[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]

B x A:
 [[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]

Форми: (4, 4) (4, 4)
Чи однакові: False


## Завдання 15. Комутатор двох матриць

Для кожної пари матриць обчисліть комутатор
\[
[A,B] = AB - BA.
\]

Перша пара:
```python
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])
```

Друга пара:
```python
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])
```

Визначте, для якої пари виконується `AB = BA`. Для перевірки використайте `np.allclose()`.

In [18]:
A1 = np.array([[3, 0], [0, 7]])
B1 = np.array([[2, 0], [0, 5]])
A2 = np.array([[0, 2], [-1, 0]])
B2 = np.array([[4, 0], [0, 1]])

comm1 = (A1 @ B1) - (B1 @ A1)
comm2 = (A2 @ B2) - (B2 @ A2)

print("Комутатор 1:\n", comm1)
print("Комутатор 2:\n", comm2)

print("AB = BA (пара 1):", np.allclose(A1 @ B1, B1 @ A1))
print("AB = BA (пара 2):", np.allclose(A2 @ B2, B2 @ A2))

Комутатор 1:
 [[0 0]
 [0 0]]
Комутатор 2:
 [[ 0 -6]
 [-3  0]]
AB = BA (пара 1): True
AB = BA (пара 2): False


## Завдання 16. Квадратична форма

Дано симетричну матрицю:
```python
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
```

1. Обчисліть квадратичну форму `xᵀAx`.
2. Для трьох векторів
```python
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])
```
обчисліть значення квадратичної форми для кожного рядка без циклу.

Для другого пункту використайте `np.einsum()`.

In [19]:
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])
x = np.array([2, -1, 3])

q_form_x = x.T @ A @ x
print("Квадратична форма для x:", q_form_x)

X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])

q_form_X = np.einsum('ij,jk,ik->i', X, A, X)
print("Значення для кожного рядка X:", q_form_X)

Квадратична форма для x: 35
Значення для кожного рядка X: [35 17 27]


## Завдання 17. Степінь матриці

Дано матрицю:
```python
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
```

1. Обчисліть `A²`.
2. Обчисліть `A³`.
3. Перевірте, що `A³ = A² @ A`.

Використайте `np.linalg.matrix_power()`.

In [20]:
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

A2 = np.linalg.matrix_power(A, 2)
A3 = np.linalg.matrix_power(A, 3)

print("A^2:\n", A2)
print("A^3:\n", A3)
print("Перевірка A^3 = A^2 @ A:", np.allclose(A3, A2 @ A))

A^2:
 [[1 2 1]
 [1 1 2]
 [2 1 1]]
A^3:
 [[2 3 3]
 [3 2 3]
 [3 3 2]]
Перевірка A^3 = A^2 @ A: True


## Завдання 18. Ранг матриці

Дано дві матриці:
```python
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
```

1. Знайдіть ранг кожної матриці.
2. Визначте, яка з них має повний ранг.

Використайте `np.linalg.matrix_rank()`.

In [21]:
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])
B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])

rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

print("Ранг A:", rank_A)
print("Ранг B:", rank_B)
print("Чи має A повний ранг?", rank_A == 3)
print("Чи має B повний ранг?", rank_B == 3)

Ранг A: 3
Ранг B: 2
Чи має A повний ранг? True
Чи має B повний ранг? False


## Завдання 19. Власні значення та власні вектори

Дано симетричну матрицю:
```python
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])
```

1. Знайдіть власні значення та власні вектори.
2. Перевірте співвідношення `A @ V = V * λ`.
3. Виведіть результат перевірки через `np.allclose()`.

Використайте `np.linalg.eigh()`.

In [22]:
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

eigenvals, eigenvecs = np.linalg.eigh(A)
print("Власні значення:", eigenvals)
print("Власні вектори:\n", eigenvecs)

check = np.allclose(A @ eigenvecs, eigenvecs * eigenvals)
print("Перевірка A @ V = V * λ:", check)

Власні значення: [2. 7.]
Власні вектори:
 [[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]
Перевірка A @ V = V * λ: True


## Завдання 20. Метод найменших квадратів

Для точок
```python
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])
```

побудуйте пряму
\[
y \approx a + bx.
\]

1. Сформуйте матрицю ознак зі стовпця одиниць і значень `x`.
2. Знайдіть коефіцієнти `a` і `b` методом найменших квадратів.
3. Обчисліть прогнозні значення `y`.
4. Знайдіть суму квадратів залишків.

Використайте `np.linalg.lstsq()`.

In [26]:
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

X = np.vstack([np.ones(len(x)), x]).T
coeffs, residuals, _, _ = np.linalg.lstsq(X, y, rcond=None)

a, b = coeffs
print(f"a = {a:.4f}, b = {b:.4f}")

y_pred = a + b * x
print("Прогнозні y:", y_pred)

rss = residuals[0] if len(residuals) > 0 else np.sum((y - y_pred)**2)
print("Сума квадратів залишків:", rss)

a = 2.0200, b = 2.0100
Прогнозні y: [ 2.02  4.03  6.04  8.05 10.06]
Сума квадратів залишків: 0.13100000000000012
